sudo: required
language: generic

services:
  - docker

after_success:
  - docker build -t mopitz/frontend-nginx-proxy ./nginx-proxy
  - docker build -t mopitz/frontend-app .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mopitz/frontend-nginx-proxy
  - docker push mopitz/frontend-app

before_deploy:
  - zip -r economicapp-frontend.zip Dockerrun.aws.json .ebextensions
  - rm Dockerrun.aws.json
  - rm -R .ebextensions

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: economicapp-frontend
  env: EconomicappFrontend-prod
  bucket_name: elasticbeanstalk-us-east-1-960622128562
  bucket_path: economicapp-frontend-prod
  zip-file: economicapp-frontend.zip
  skip_cleanup: true
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
