sudo: required
language: generic

services:
  - docker

after_success:
  - docker build -t mopitz/frontend-nginx-proxy ./nginx-proxy
  - docker build -t mopitz/frontend-app .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mopitz/frontend-nginx-proxy
  - docker push mopitz/frontend-app
